version: '2'
services:
    jhipster_websocket_spring-app:
        image: jhipster_websocket_spring
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://jhipster_websocket_spring-mysql:3306/jhipster_websocket_spring?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jhipster_websocket_spring-mysql:
        extends:
            file: mysql.yml
            service: jhipster_websocket_spring-mysql
